"""
Django settings for ncasign project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!e+^4)!(5uckchhrw9po3q181qvj)p^a=xdm-_6r&v_r47ml*r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ncasign',
    'documents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ncasign.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'ncasign' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ncasign.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'ncasign.User'

DROPBOX_TOKEN = 'sl.u.AF35OW9C_K6POI52ysIaP47iVn1u3voIWi_ZoGyfiHFemP9DkjQfZX9knCYJRuf2G-l4sB4NxXYykKcT6Wy6eeEB00746ACu6fWP2oVfOV82SVPpL2UzYNTA91KWhz5rDQM1TPjkcFLWn9Nqd_dzDHga74f0gqMhVD2ghDvBN_6aWSHfADFTpNuU6jh4m6ZuOZHrnluQteZ77P2i09nD9MVzpTMRnPRyCoOGIoMV0o6el1c2GR3EOMPRbA7zpC3P16e5Buf6ZUnCGt46pcFsrYVbNFEOnarlMonZJgl0v3tgSS1Eir8py3JSN6C9asFBdw_fwmBcd_Ma10cg2R_SULy3Fdb_vgCD3TwBzLpWi0MZLj8pk_5JG_BIhwdhrzP7pTTGq4tOQpkIA4JSa7FuiQkolGoV2qeRDU8edCGFV74sgoywOkZvMvkM7NpAeJltv3F18ZXr-t_7Vyl33curA8Dj8EKrxziUzPO8NGTcn5ZNSr4iGT2qofXlk5FA6LsKuBvV4reocJGPERyv102Cn4lBS9eJYqXMuJiPb4EP0mXnQdkBEmJFYO-lioxayhh18KNuP5RgD-z2f8AJPM2G1gdr5R4kXhIaLaSdIwR6oSTP98XhmEEzCnb9UWb0XEpZ4NgRR_-qv902FyAfeZBawUEuFHOmvlBnUb0Ngx2c7l-s7UPs8VzgnHaEP_KzpK6hbjyUsljNN046yGJbtMF2f6u39Z8ryuZWq3DyqSNlOm0Chju23pqrYl2AIUsNngHpaoirxBa9Hi3PAEqF3gHnfslHEtXkWM0otmUurTBu0ooJhbpNcggo_9f37Y9rYpSXmlPI4kCaez7YKyNs4Q84KwznbexE2NRUsRGTGoXN0HGi1fSBNWi-QQpDUtK2F3sffbljp9PLPIQR1-qLrtEyaWI8UGrNqI0Ydmd7wN9sIsbrCB8uDlyLKk7kdZ_8sOvh2E4Y89Y84Up6MMtNiZ3v5zp4F7NMnvC0HVNOEyfm01k6CDxvDB7W3GjynFkxlFSy76-DbrZw8Luodx9RCxnVZY927pFpkV72LpwaXj2f9XXlsyKXCv6Wmt9mzO3SLPvi9N0DRfO0GFACmzyR_Id5CJhU8IB1RSFtSB24Wqahtbqxs8FYow1SrNmqZiXd0ffCdoO3H2QroBo-fbNcoOTts8n_51jEligYWU3nmV0cwO89NKNcddjdb3vTyBJGIbdO8iSAiyJ8DTdUVJorrKxc0ix5XgjjwpbhUHNPq162P1fY-pfavykLbN1af2BSfPmaNIZd15arn4FMv65whbfR2TtcIxcjeEgq3whL8mHt-HxCx1F8Ma9HuV-3Xd6rmWYE7SE'