"""
Django settings for ncasign project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!e+^4)!(5uckchhrw9po3q181qvj)p^a=xdm-_6r&v_r47ml*r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ncasign',
    'documents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ncasign.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'ncasign' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ncasign.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'ncasign.User'

DROPBOX_TOKEN = 'sl.u.AF2Ds4WzrwFOKiByfapaZ9tvPHuc-mL0S37j8E0P9eRh8l_dvD5HLFOJV1yjY6jaBr9PiQXXWXrKeQcD3pr_ti4oNXMwY9Dpen-q3jnKUgcnhC-DmAJ6Q7U2j9T1bosFqnj97VJtWCRYhp9UyQhRneRPKe0PsrZq1ASjN_qZJv95U3bMvLlEzBN2Mm19-v9tSbypgvzu5uz0Dvk16onIHwczljKcle0312UYGzMbYxWC6KXFEAZHT8ozEfiwJAAiEcedDtD0NYz5Nuf6vC-Sp0GQTK1ptYiwf5Sza6b9DPmaiPA1AQjXOrGRJ2JrH7xk-qV8Tz6UjirH3R_SlBR79ku4jS0fwrzaSRCGqf6xtfd9f2qWOyQq-en06Fadj5oJ67GIg6qD6bpAMZ-noaIeMH6rwlDRbr0qrLZ9m2doADsCWcv7mBS0fFwGDBZXmYO5HtNx0SJnMzKg5fZFZBgIBH89SHoN91tFfYD_ZeaNxq2_v9l8nFNW0OdhOUfLal6bberjNwEUWasuz0Mw87fFc8z21aKKYuwXJQpDh4ECtTz5ADiA4TymGRKurL65YH-bBEN07-gyF0utUSuMTm69DXt3bGKP_tfD0UjQETk7v8S00JhyLZMgSynV_lx9pyknokl6u_wOeAzV0UOhjA2n_p51XpT6HWf-gfxwL-YjMUql64rOEdW49SBGkW1ahA0bjn-QQ0NvOCUn9Ceg-aSjaJg4SSQ_W_JvpTqCOzayhA3Yzk5dRPcvndKJhxIrKtpo4MNWyr5bYmnJCeEBMIBxbDdGptqB7H8PUdvjmUTUi8MQrM8SWWWlqGye9GESGepxA0rfoUwJJ2x3TGm07qvnSHvT04FdWriWceKMvzkOQNQFzbiJPfVtion9gAqL3FMB62snFThYXSpXaBNbCDQdSPOwf66CsW41eRiRgDjdwO0cr42gMlPJ0rPbFaNfanwJZaTCQY02WvFD9aehOiilzqJVPHgoFEUFy61mrhrpuU5win7IW9Kh4SV2jVTUmimWTRt9gz2GY6Liejc3P4qfF8BniO7QTyA--oGUQ6zUa8457kVTyreII-9rQUnbPfCGvLsDkxEaNqBytsRSYI6lXlftzIaor_gYt2m4waMuv949GzKiGk7fhHuHoat7sCcFg3M-VmFYeS5J78WOwTmT1Hv90sN3QqRR03lY-rS-ei6p2lJBAo6QxUR2WuS0SddXNvsTEfh11Y3y9wlt7IF5PzlZIKmfoxG_N7w_FANq7YEADPAWBsPN748XFD6J-CxbZHGfEyecKYpG9vLn-JcipWw0BiB2aiw28mv8rL74EH5dyyOw0WN7cD25SrIzP0KGBmk'