"""
Django settings for ncasign project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!e+^4)!(5uckchhrw9po3q181qvj)p^a=xdm-_6r&v_r47ml*r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ncasign',
    'documents',
    'signers',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ncasign.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'ncasign' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ncasign.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'ncasign.User'

DROPBOX_TOKEN = 'sl.u.AF36vl57DPooxIe8NZtenFjfVi5tmTK7iKSTkCCqfQJNTgFJs0KWiBCcAH07yDg_5KQTtFiWLrLjVvVDNETrO0irTgip_-b-3TdnOvpCD7maPxSctER-b5xBib9vzfN9XewTYbl8VB2lktDYs6NDq-rMt2Q0c_XDlX1OM6Ihiact7o4JcjGRJVHJbez4aNCpdCc4etXFm-7_EHHjFiIk5VSBI6xGptiAbIE0_XqXV0hMsoo9DOODgA-W3S1DgeRhyHMiNE4ObZDs5YdwKe6HgJejkcsoojZih2n3MZ86ZWRiRYS5nXRzeu7UxXQZc2wCR16uVXjdugfDDzVTQH7ccMpZcSZHCIOA_WFshUFIGu9RLtly316PIbqNP2pyN5SdnEWgohCIoURtE1TQMBRA9t4cfS27TAtMUywRC5K997nJYF_vYpFm1vafHLSn34-K7Lc7mU28ex39eusp5KfANYvPgEVaTXaBa_WyFH8f60PRzIb3nzwoP_Oa9kTd9aKgFuonG5iZ6AoL8zXX9n1A2eTUIfRGtKbPpB6yzbGJ7sAT_sVgbXGCmWh-86d12D3lmciCqFiOWadfD3wpUSqlIQrwBywFhDoA_pm9np-1j9gIZxtq6g3I-MDX7bt0CvDy7YGMON65OZamqLZWTCbCcndhqIO7f__qmEOI0cBXdMg25lXJ29DWbf0aMGMGU6Bv9bc1WiHj-DYf_-hSRnLYQgk4c685hFLUETm0QPXZ9DvB-utDmM6cG3FMRjcAfpUYTzXkeQkfZRqBURHmuNMXfwp-LrNEkhPmpJFvrD9IFePdhwJDQVOn40tkIXi4GRj4FqU94TQrgrusYb-RakA2c6j9NvL80RPiNR60x_MGmmqnryY7ijOvA_gFIDL3IEQ2MCqAhE7dYTrx7D-6aL0LPDqeYfn0WlcgWcEAPdLm_xakrP-av2ZP4H7vhWFzsvFm4ITgKqjaTsmOp1BfR4xbUdD7qx103AdtbQhm0-vA-F7bSPiF9a8Wb6_0frRbOmKCxApq5oWX8QaNHUn7b1pM1JE8w0Mvxudnaf7AwnLr0U9ZmugwduxGYaEGTVGqC3-hbO_SEtdpAPfD3TOa-_HgoXnF7ybq_Afq5ADsqUv6aD0rzONl6_xpNSfnhJLFHf11nHPXBWL_gWDg4GdO-IYYGUY_MRm9rXP7W8_MPhvD61_b3pz54ZsiBi6QLMZisxQ8WPGboT09md_iLPQu_J3WuVOiFdv0b1nAL8B4eTakPb_U04LclLUHQjyvTGv0D8j71N5ko6whDJtBxbfQgm9fVMMwbcwmxWJ2BVSTgXjcKODfiFbsuqMWrDCcX6Zzd7U9guM'
DROPBOX_APP_KEY = 'htytb26oqllts8e'
DROPBOX_APP_SECRET = 'aohqduhcn7sknru'
DROPBOX_REFRESH_TOKEN = 'VyivhetD6MgAAAAAAAAAAQj-D_H_bArVWbn3m45oNTCwVuxWfuL1HKKGjj1QtVPS'

"https://www.dropbox.com/oauth2/authorize?client_id=htytb26oqllts8e&token_access_type=offline&response_type=code"

X_FRAME_OPTIONS = 'SAMEORIGIN'



