# Generated by Django 5.2.4 on 2025-07-15 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GphDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=50, unique=True, verbose_name='ID документа')),
                ('doc_type', models.CharField(choices=[('gph', 'ГПХ договор'), ('act', 'Акт выполненных работ')], max_length=10, verbose_name='Тип документа')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО исполнителя')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('file_path', models.CharField(max_length=255, verbose_name='Публичная ссылка на файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания (секунды)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Договор ГПХ',
                'verbose_name_plural': 'Договоры ГПХ',
                'db_table': 'gph_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
