# Generated by Django 5.2.4 on 2025-07-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_gphdocument_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='gphdocument',
            name='approvers',
            field=models.JSONField(default=list, verbose_name='Согласующие'),
        ),
    ]
