# Generated by Django 5.2.4 on 2025-07-16 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_gphdocument_approvers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_id', models.CharField(max_length=50, unique=True, verbose_name='ID акта')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО исполнителя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('iin', models.CharField(max_length=12, verbose_name='ИИН')),
                ('start_date', models.DateField(verbose_name='Дата начала работ')),
                ('end_date', models.DateField(verbose_name='Дата окончания работ')),
                ('quantity', models.CharField(max_length=50, verbose_name='Количество')),
                ('unit_price', models.CharField(max_length=50, verbose_name='Цена за единицу')),
                ('amount', models.CharField(max_length=50, verbose_name='Общая стоимость')),
                ('file_path', models.CharField(max_length=255, verbose_name='Публичная ссылка на файл')),
                ('approvers', models.JSONField(default=list, verbose_name='Согласующие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('gph_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.gphdocument', verbose_name='ГПХ договор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Акт выполненных работ',
                'verbose_name_plural': 'Акты выполненных работ',
                'db_table': 'act_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
