# Generated by Django 5.2.4 on 2025-07-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_actpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='actdocument',
            name='actions',
            field=models.JSONField(default=list, verbose_name='Этапы согласования и подписания'),
        ),
        migrations.AddField(
            model_name='gphdocument',
            name='actions',
            field=models.JSONField(default=list, verbose_name='Этапы согласования и подписания'),
        ),
    ]
