# Generated by Django 5.2.4 on 2025-07-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_actdocument_actions_gphdocument_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actdocument',
            name='approvers',
        ),
        migrations.RemoveField(
            model_name='gphdocument',
            name='approvers',
        ),
    ]
