# Generated by Django 5.2.4 on 2025-07-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_actdocument_approvers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actdocument',
            name='additional_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Сведения об отчете'),
        ),
        migrations.AddField(
            model_name='actdocument',
            name='text',
            field=models.CharField(default='', max_length=255, verbose_name='Наименование работ (услуг)'),
        ),
        migrations.AddField(
            model_name='actdocument',
            name='unit',
            field=models.CharField(default='месяц', max_length=50, verbose_name='Единица измерения'),
        ),
    ]
