# Generated by Django 5.2.4 on 2025-07-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_actdocument_attachments_gphdocument_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='actdocument',
            name='total_amount',
            field=models.CharField(default='0', max_length=50, verbose_name='Общая стоимость'),
        ),
        migrations.AddField(
            model_name='actdocument',
            name='total_quantity',
            field=models.CharField(default='0', max_length=50, verbose_name='Общее количество'),
        ),
        migrations.AddField(
            model_name='actdocument',
            name='total_sum',
            field=models.CharField(default='0', max_length=50, verbose_name='Общая цена за единицу'),
        ),
        migrations.AddField(
            model_name='actdocument',
            name='works',
            field=models.JSONField(default=list, verbose_name='Список работ/услуг'),
        ),
        migrations.AlterField(
            model_name='actdocument',
            name='additional_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Сведения об отчете (устарело)'),
        ),
        migrations.AlterField(
            model_name='actdocument',
            name='amount',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Общая стоимость (устарело)'),
        ),
        migrations.AlterField(
            model_name='actdocument',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания работ'),
        ),
        migrations.AlterField(
            model_name='actdocument',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Количество (устарело)'),
        ),
        migrations.AlterField(
            model_name='actdocument',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала работ'),
        ),
        migrations.AlterField(
            model_name='actdocument',
            name='text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Наименование работ (устарело)'),
        ),
        migrations.AlterField(
            model_name='actdocument',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Единица измерения (устарело)'),
        ),
        migrations.AlterField(
            model_name='actdocument',
            name='unit_price',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Цена за единицу (устарело)'),
        ),
    ]
