# Generated by Django 5.2.4 on 2025-07-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncasign', '0003_alter_user_managers_remove_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Username'),
        ),
    ]
