# Generated by Django 5.2.4 on 2025-07-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncasign', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Админ'), (2, 'Подписант'), (3, 'Согласующий'), (4, 'Исполнитель'), (5, 'Редактор')], default=4, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='Username'),
        ),
    ]
