# Generated by Django 5.2.4 on 2025-07-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncasign', '0006_user_iin_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proxy_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доверенности'),
        ),
        migrations.AddField(
            model_name='user',
            name='proxy_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер доверенности'),
        ),
    ]
